import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./NextAuthProviders";
import "./globals.css";
import { UserSubscriptionProvider } from "./(context)/UserSubscriptionContext";
import { UpdateCreditUsageProvider } from "./(context)/UpdateCreditUsageContext";
import { TotalUsageProvider } from "./(context)/TotalUsageContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <UserSubscriptionProvider>
            <UpdateCreditUsageProvider>
              <TotalUsageProvider>{children}</TotalUsageProvider>
            </UpdateCreditUsageProvider>
          </UserSubscriptionProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
